### ISSUE TITLE
[Document bug] wrong picture in architecture page

### ISSUE THREAD

**Issue by xibuka** [longhorn/website#149]
In the `architecture` page of Longhorn 1.0 and 0.8.1, the last picture is duplicated with its previous one, and I believe there should be another correct one.

https://longhorn.io/docs/1.0.0/architecture/
https://longhorn.io/docs/0.8.1/architecture/

**Comment by catherineluse** [comment]
This is fixed in this PR https://github.com/longhorn/website/pull/147

After those changes are merged, another PR can replicate the same changes for previous doc versions.

**Comment by jenting** [comment]
I believe this issue is fixed already, close it.
