### ISSUE TITLE
Clarify locality of data vs pods

### ISSUE THREAD

**Issue by janeczku** [longhorn/website#152]
The documentation overall and especially the architecture pictures can leave the impression that any node running a pod consuming a volume also runs a replica for that volume.

https://longhorn.io/docs/1.0.0/architecture/

I think it should be made much clearer that LH volumes are basically (via the controller) provided as network storage and can be attached to any worker node, not just the ones providing the storage for the replicas.

Suggestion:
Update the architecture diagram to show a pod running on a node without a replica.

**Comment by yasker** [comment]
@janeczku That's a good point. @catherineluse We can discuss how we want to improve it.

**Comment by innobead** [comment]
Closing this. We can follow up with any suggestion on longhorn/longhorn repo instead.
