### ISSUE TITLE
Broken "Customize default settings" link on "Taints and Tolerations" page

### ISSUE THREAD

**Issue by ttpcodes** [longhorn/website#156]
The instructions on the [Taints and Tolerations page](https://longhorn.io/docs/1.0.0/advanced-resources/deploy/taint-toleration/) for `v1.0.0` tell a user to go to the "Customize default settings" page to find the instructions for setting the initial taint tolerations, but that link points to a nonexistent wiki link on longhorn/longhorn.

**Comment by rdxmb** [comment]
I stumbled over that, too. It would be great to have documented, how the toleration settings can be set via the deployment.

**Comment by yasker** [comment]
@rdxmb The link should be https://longhorn.io/docs/1.0.2/advanced-resources/deploy/customizing-default-settings/ . We will update it soon.

**Comment by yasker** [comment]
Fix merged.
