### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by samamoateng** [longhorn/website#194]
Add a license to the repository.

**Comment by flarely** [comment]
I'm willing to do this, what license do you think should be added?

**Comment by nate-double-u** [comment]
Over on the dexidp.io [site repo](https://github.com/dexidp/website) they went with Apache 2.0. [Here's some discussion](https://github.com/dexidp/website/pull/9#issuecomment-702372163) as to why.

**Comment by yasker** [comment]
@nate-double-u Yeah, we will go with Apache 2.0 too.

**Comment by geenva** [comment]
Okay.
