### ISSUE TITLE
Add Knowledge Base section to the website

### ISSUE THREAD

**Issue by yasker** [longhorn/website#197]
https://github.com/longhorn/longhorn/issues/1783

So we can start answering the most common questions, as well as provide the doc as the source instead of asking users to check the GitHub issue thread.

**Comment by hackabletype** [comment]
Hi @yasker, I can take a look at this.

Should this work more like the current Blog page (a collection of pages each containing a KB item), or the Project page (a single page with a list of all the KB items), or should it more closely mimic the actual docs architecture? Or did you have something else entirely in mind?

**Comment by yasker** [comment]
Thanks @hackabletype . I think it would be similar to the current Blog pages since KB articles are less organized than the doc. As long as it's easy for the user to search through the whole repo, it should be fine.

**Comment by yasker** [comment]
Done by https://github.com/longhorn/website/pull/198
