### ISSUE TITLE
Find new secondary color

### ISSUE THREAD

**Issue by lucperkins** [longhorn/website#20]
The current `$secondary` color (#EA3A3A), which is a holdover from the original Longhorn site, is a bit jarring and doesn't quite mesh with the current site (you can see it in action on the **Learn more** button on the main page). It'd be nice to find something that complements the Longhorn maroon a bit better.

@yasker Can you assign @celestehorgan to this?

**Comment by yasker** [comment]
Thanks @lucperkins @celestehorgan . Though I cannot assign to @celestehorgan before she comments on the issue (per https://help.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users )

**Comment by lucperkins** [comment]
@yasker No worries. I'll let her know.

**Comment by celestehorgan** [comment]
I'm here, I'm here! 

By way of introduction to you all and the project – I'm with the CNCF working as a tech writer/designer/docs wrangler at large. Hello! :)

**Comment by yasker** [comment]
Thanks @celestehorgan ! We might ask your help with improving the document in the future too. :)
