### ISSUE TITLE
Algolia search doesn't work for blog and knowledge base

### ISSUE THREAD

**Issue by yasker** [longhorn/website#200]
Ref: https://github.com/longhorn/website/pull/198#issuecomment-701710159

**Comment by yasker** [comment]
cc @jrcreate

**Comment by yasker** [comment]
cc @jrcreative

**Comment by jenting** [comment]
It needs to contact Algolia support engineer, to add blog and knowledge base URL to the `config.json`
```json
   "start_urls": [
        "https://longhorn.io/docs/",
	"https://longhorn.io/blog/",
	"https://longhorn.io/kb/"
  ],
```

**Comment by jenting** [comment]
It's searchable right now, close it.
