### ISSUE TITLE
Add concepts documention pulled from architecture blog

### ISSUE THREAD

**Issue by JasonvanBrackel** [longhorn/website#25]
Missing items from this section of the documentation from https://github.com/longhorn/website/issues/17 will be pulled from [this blog post](https://rancher.com/blog/2017/announcing-longhorn-microservices-block-storage/).

Longhorn Concepts
```
- Volumes
- Snapshots
- Backups
  - Backup Stores
  - Backup Targets
  - Disaster Recover Volumes
```

**Comment by yasker** [comment]
Fixed by #31
