### ISSUE TITLE
Alert LonghornNodeDown example in documentation doesn't work.

### ISSUE THREAD

**Issue by Turb0Fly** [longhorn/website#382]
The prometheus alert LonghornNodeDown as seen on https://longhorn.io/docs/1.2.0/monitoring/alert-rules-example/ does not work.
`longhorn_node_total - (count(longhorn_node_status{condition="ready"}==1) OR on() vector(0))`

The metric **longhorn_node_total** does not exist. When querying the metrics , **longhorn_node_count_total** is there.  However, replacing the metric with the correct one in the expression does not work either.  When forcing a node down, the alert is never fired but querying the metric gets the correct value.

Using Longhorn 1.1.0
Rancher 2.5.8
Rancher Monitoring 14.5.100

We need an expression that will fire only when a node is not ready and not just on count, e.g. getting an alert when value is 0.

FWIW, I came up with something that works :
`(avg(longhorn_node_count_total) or on() vector(0)) - (count(longhorn_node_status{condition="ready"} == 1) or on() vector(0)) > 0`

**Comment by jenting** [comment]
Issue moved to [longhorn/longhorn #3729](https://github.com/longhorn/longhorn/issues/3729) via [**ZenHub**](https://www.zenhub.com/)
