### ISSUE TITLE
Need to increase contrast of syntax highlighting to meet accessibility standards.

### ISSUE THREAD

**Issue by catherineluse** [longhorn/website#46]
The purple-on-purple highlighting is going to be difficult for people with low vision.
<img width="442" alt="Screen Shot 2020-04-13 at 12 47 24 PM" src="https://user-images.githubusercontent.com/20599230/79154749-f81c9800-7d84-11ea-9f86-42836489234a.png">

**Comment by lucperkins** [comment]
@catherineluse You can see the available themes here: https://xyproto.github.io/splash/docs/all.html

**Comment by jenting** [comment]
I see the current theme change to a gray background, this is more readable than purple.
![image](https://user-images.githubusercontent.com/49380831/118218135-690f1180-b4a9-11eb-8e6c-0c4e7c9abf82.png)


Close it since I think it's fixed.
