### ISSUE TITLE
Need a `search` function for the website

### ISSUE THREAD

**Issue by yasker** [longhorn/website#52]
It will help a lot if we can provide a website search to user. `docs` search is good enough for the first step.

**Comment by lucperkins** [comment]
I've applied to have the site scraped by [Algolia DocSearch](https://docsearch.algolia.com). That usually takes about a week. Once that's done, longhorn.io can have a search bar like the one you see here: https://keda.sh.

**Comment by yasker** [comment]
Great, thanks @lucperkins !

**Comment by yasker** [comment]
Fixed by https://github.com/longhorn/website/pull/59
