### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by krumware** [longhorn/website#521]
It appears that search currently isn't working on the docs site:
![image](https://user-images.githubusercontent.com/17303782/173920446-090ea6bd-a086-4633-a5c0-59b045a92a38.png)

Thank you for longhorn!

**Comment by derekbit** [comment]
Work expected now.
![image](https://user-images.githubusercontent.com/12527233/175510389-e07a2695-f34a-47ff-a44b-b5bcfa9d4dac.png)

**Comment by derekbit** [comment]
Feel free to open it if you still run into the error. Thank you.
