### ISSUE TITLE
Scan for old links

### ISSUE THREAD

**Issue by yasker** [longhorn/website#55]
Otherwise, if an external link disappears, we won't know until getting the next PR.

**Comment by lucperkins** [comment]
@yasker Actually, at the moment there's no external link checking in PRs, only internal.

**Comment by yasker** [comment]
I see. Is there any way we can manually scan the external link? I saw an old link to `longhorn/longhorn` docs we didn't catch.

**Comment by catherineluse** [comment]
Yilin Zeng (a technical writer in Shenzhen) shared with me a helpful free tool that can scan all the links. https://www.brokenlinkcheck.com/

**Comment by caniszczyk** [comment]
FYI there's a lot of broken link checkers available via github actions

see what you may want, i.e., https://github.com/marketplace/actions/broken-link-checker-action

**Comment by jenting** [comment]
I see we have a GitHub action to scan the broken link, I think it's got addressed already, close it.
Feel free to reopen it if there are any concerns.
