### ISSUE TITLE
Update the Longhorn document in Using the Environment Check Script

### ISSUE THREAD

**Issue by Lichiehyao** [longhorn/website#569]
## Environment

 - Longhorn version:1.3.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:n/a
   - Number of management node in the cluster:1
   - Number of worker node in the cluster:3
 - Node config
   - OS type and version: ubuntu 20.04
   - CPU per node: 4 cores
   - Memory per node:8GB
   - Disk type(e.g. SSD/NVMe):n/a
   - Network bandwidth between the nodes:n/a
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):KVM
 - Number of Longhorn volumes in the cluster:

## Describe the bug

After execuetd [using-the-environment-check-script](https://longhorn.io/docs/1.4.0/deploy/install/#using-the-environment-check-script) , I found out the console output different from the document.  

[Quick Installation](https://longhorn.io/docs/1.4.0/deploy/install/)

Example result on the document

```shell
daemonset.apps/longhorn-environment-check created
waiting for pods to become ready (0/3)
all pods ready (3/3)
  MountPropagation is enabled!
cleaning up...
daemonset.apps "longhorn-environment-check" deleted
clean up complete
```

Since v1.3.1, console output result:

```shell
[INFO]  Required dependencies are installed.
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/3)...
[INFO]  All longhorn-environment-check pods are ready (3/3).
[INFO]  Required packages are installed.
[INFO]  Cleaning up longhorn-environment-check pods...
[INFO]  Cleanup completed.

```

## Expected behavior

We need to update the document since 1.3.1+.

**Comment by innobead** [comment]
@Lichiehyao Please create an issue in longhorn/longhorn instead. That is the only place we trace issues.
