### ISSUE TITLE
Forwarding `docs.longhorn.io/xxx` to `longhorn.io/docs/xxx`

### ISSUE THREAD

**Issue by yasker** [longhorn/website#65]

**Comment by yasker** [comment]
I've tried to update https://github.com/longhorn/website/blob/master/layouts/index.redirects but it still doesn't work...

@lucperkins Do you have some time to help us with this?

**Comment by lucperkins** [comment]
@yasker That won't work because redirects can only be applied to links relative to the `longhorn.io` root, and routing from a subdomain like `docs` to a specific path is not possible.

**Comment by yasker** [comment]
@lucperkins Netlify support said there is one way that might work:

>Should be possible:
> 1. set up DNS for docs.longhorn.io.  That should be a CNAME to longhornio.netlify.app
> 2. add a domain redirect (https://docs.netlify.com/routing/redirects/redirect-options/#domain-level-redirects) to that site.  If you use _redirects, I'd add this line to the TOP:  `https://docs.longhorn.io/* https://longhorn.io/docs/:splat 301!`
> 3. add docs.longhorn.io to some netlify site's DNS configuration, likely this one: https://app.netlify.com/sites/longhornio/settings/domain#custom-domains
> 4. wait for SSL provisioning to complete
> 5. test the redirect.

I think the second one is referring to https://github.com/longhorn/website/blob/master/layouts/index.redirects ? What do you think?

**Comment by yasker** [comment]
Seems doesn't work...

**Comment by lucperkins** [comment]
Try it again in a few hours on a fresh browser and such, just to make sure that the DNS is all properly resolved

**Comment by yasker** [comment]
Subpath under `docs.longhorn.io` works now after https://github.com/longhorn/website/pull/105 . But docs.longhorn.io itself still pointed to longhorn.io instead of longhorn.io/docs .

**Comment by yasker** [comment]
Alright, this redirect is still a bit weird.

`docs.longhorn.io` is redirect to `longhorn.io/docs` which is good.

But `docs.longhorn.io/0.8.1/` doesn't exist. And `docs.longhorn.io/docs/0.8.1/` does exist...

**Comment by yasker** [comment]
It finally works now! @lucperkins @catherineluse 

There is one redirect rule in `_redirects` missing a return line. Probably due to how we generate `_redirects`.

Now following URLs work as expected:
https://docs.longhorn.io/
https://docs.longhorn.io/0.8.0/
https://docs.longhorn.io/0.8.1/
https://docs.longhorn.io/latest/
https://docs.longhorn.io/concepts/
http://docs.longhorn.io/snapshots-and-backups/backup-and-restore/set-backup-target/

**Comment by yasker** [comment]
Fixed.
