### ISSUE TITLE
Build the staging website

### ISSUE THREAD

**Issue by yasker** [longhorn/website#75]
We want to build a version of website from the `staging` branch so contributors can know what's the update on the incoming documents. Probably at `staging.longhorn.io`?

The `staging` branch will always be used for the next release version.

**Comment by yasker** [comment]
@lucperkins Do you have some time to help with this? Thanks!

**Comment by lucperkins** [comment]
@yasker The staging site is currently available at https://staging--longhornio.netlify.app. You can add a CNAME for that here: https://app.netlify.com/teams/longhorn/dns/longhorn.io.

**Comment by yasker** [comment]
Thanks @lucperkins , it works now.

However, I found I cannot redirect `docs.longhorn.io` to `longhorn.io/docs`. Netlify doesn't allow me to change `docs.longhorn.io`, not sure what's wrong here..

**Comment by yasker** [comment]
Done

**Comment by yasker** [comment]
Staging at: https://staging.longhorn.io
